import re


HEADER_PATTERNS = [
    r"Company Confidential",
    r"Internal Use Only",
    r"Page\s+\d+\s+of\s+\d+",
]

FOOTER_PATTERNS = [
    r"Confidential",
    r"Generated by.*",
]


def remove_headers(text: str) -> str:

    for pattern in HEADER_PATTERNS:
        text = re.sub(
            pattern,
            "",
            text,
            flags=re.IGNORECASE,
        )

    return text


def remove_footers(text: str) -> str:

    for pattern in FOOTER_PATTERNS:
        text = re.sub(
            pattern,
            "",
            text,
            flags=re.IGNORECASE,
        )

    return text