from pathlib import Path
import shutil
import tempfile

import opendataloader_pdf
import pymupdf as fitz
from loguru import logger

from app.ingestion.schemas import ParsedDocument, ParsedPage


class OpenDataLoaderParser:

    def parse(self, pdf_path: str | Path) -> ParsedDocument:

        pdf_path = Path(pdf_path)

        output_dir = Path(tempfile.mkdtemp())

        try:
            logger.info(f"Parsing {pdf_path.name} using OpenDataLoader...")

            opendataloader_pdf.convert(
                input_path=[str(pdf_path)],
                output_dir=str(output_dir),
                format="markdown",
            )

            markdown_files = list(output_dir.rglob("*.md"))

            if not markdown_files:
                raise RuntimeError("No markdown generated by OpenDataLoader.")

            markdown = markdown_files[0].read_text(
                encoding="utf-8",
                errors="ignore",
            ).strip()

            # Get actual page count from PDF
            with fitz.open(pdf_path) as pdf:
                page_count = len(pdf)

            # Decide whether OCR is needed
            needs_ocr = (
                len(markdown) < 50
                or len(markdown.split()) < 20
            )

            logger.info(
                f"Markdown characters: {len(markdown)} | "
                f"Needs OCR: {needs_ocr}"
            )

            return ParsedDocument(
                document=pdf_path.name,
                file_type="pdf",
                page_count=page_count,
                total_characters=len(markdown),
                needs_ocr=needs_ocr,
                ocr_used=False,
                pages=[
                    ParsedPage(
                        document=pdf_path.name,
                        page=1,
                        text=markdown,
                        needs_ocr=needs_ocr,
                    )
                ],
            )

        except Exception as e:
            logger.exception(e)
            raise RuntimeError(
                f"OpenDataLoader parsing failed: {e}"
            )

        finally:
            shutil.rmtree(output_dir, ignore_errors=True)